#!/usr/bin/env bash

#cd ${0%/*} || exit 1

./Allclean
blockMesh
sed -i "/controls-start/,/controls-end/{/castellated*/{s/.*/castellatedMesh\ton;/}}" ./system/snappyHexMeshDict
sed -i "/controls-start/,/controls-end/{/snap*/{s/.*/snap\toff;/}}" ./system/snappyHexMeshDict
snappyHexMesh -overwrite
extrudeMesh
sed -i "/controls-start/,/controls-end/{/castellated*/{s/.*/castellatedMesh\toff;/}}" ./system/snappyHexMeshDict
sed -i "/controls-start/,/controls-end/{/snap*/{s/.*/snap\ton;/}}" ./system/snappyHexMeshDict
checkMesh
#snappyHexMesh -overwrite
#potentialFoam > logp &
