#!/usr/bin/env bash

#cd ${0%/*} || exit 1

./Allclean
fluentMeshToFoam file_f2.msh
sed -i "/empty/{n;n;s/.*/\t\ttype\t\t\tempty/}" ./constant/polyMesh/boundary
simpleFoam > log &
sleep 5
foamMonitor -l postProcessing/residuals/0/residuals.dat &
sleep 1
foamMonitor postProcessing/forcesIncompressible/0/forces.dat &

